name: PoC Expression Injection - Issue Body
on:
  issues:
    types: [opened]
jobs:
  poc:
    runs-on: ubuntu-latest
    steps:
      - name: test-injection
        run: |
          BODY="${{ github.event.issue.body }}"
          echo "Body: $BODY"
